/**
 * @namespace: addons/adventure/helpers/items.js
 * @type: Helper Script
 * @copyright © 2026 kenndeclouv
 * @assistant graa & chaa
 * @version 1.0.0-rc
 */

const items = {
	equipment: [
		{
			id: 'stick',
			emoji: '🪵',
			nameKey: 'adventure.shop.items.stick.name',
			descKey: 'adventure.shop.items.stick.desc',
			price: 5,
			buyable: true,
			sellPrice: 2,
			type: 'equipment',
			stats: { attack: 1 },
		},
		{
			id: 'rock',
			emoji: '🪨',
			nameKey: 'adventure.shop.items.rock.name',
			descKey: 'adventure.shop.items.rock.desc',
			price: 8,
			buyable: true,
			sellPrice: 3,
			type: 'equipment',
			stats: { attack: 2 },
		},
		{
			id: 'dagger',
			emoji: '🗡️',
			nameKey: 'adventure.shop.items.dagger.name',
			descKey: 'adventure.shop.items.dagger.desc',
			price: 20,
			buyable: true,
			sellPrice: 10,
			type: 'equipment',
			stats: { attack: 5 },
		},
		{
			id: 'wooden_club',
			emoji: '🏏',
			nameKey: 'adventure.shop.items.wooden_club.name',
			descKey: 'adventure.shop.items.wooden_club.desc',
			price: 25,
			buyable: true,
			sellPrice: 12,
			type: 'equipment',
			stats: { attack: 6 },
		},
		{
			id: 'slingshot',
			emoji: '🏹',
			nameKey: 'adventure.shop.items.slingshot.name',
			descKey: 'adventure.shop.items.slingshot.desc',
			price: 30,
			buyable: true,
			sellPrice: 15,
			type: 'equipment',
			stats: { attack: 7 },
		},
		{
			id: 'short_sword',
			emoji: '🗡️',
			nameKey: 'adventure.shop.items.short_sword.name',
			descKey: 'adventure.shop.items.short_sword.desc',
			price: 40,
			buyable: true,
			sellPrice: 20,
			type: 'equipment',
			stats: { attack: 8 },
		},
		{
			id: 'training_sword',
			emoji: '🎋',
			nameKey: 'adventure.shop.items.training_sword.name',
			descKey: 'adventure.shop.items.training_sword.desc',
			price: 15,
			buyable: true,
			sellPrice: 7,
			type: 'equipment',
			stats: { attack: 4 },
		},

		{
			id: 'bronze_sword',
			emoji: '🥉',
			nameKey: 'adventure.shop.items.bronze_sword.name',
			descKey: 'adventure.shop.items.bronze_sword.desc',
			price: 60,
			buyable: true,
			sellPrice: 30,
			type: 'equipment',
			stats: { attack: 10 },
		},
		{
			id: 'bronze_axe',
			emoji: '🪓',
			nameKey: 'adventure.shop.items.bronze_axe.name',
			descKey: 'adventure.shop.items.bronze_axe.desc',
			price: 70,
			buyable: true,
			sellPrice: 35,
			type: 'equipment',
			stats: { attack: 12 },
		},
		{
			id: 'iron_sword',
			emoji: '⚔️',
			nameKey: 'adventure.shop.items.iron_sword.name',
			descKey: 'adventure.shop.items.iron_sword.desc',
			price: 100,
			buyable: true,
			sellPrice: 50,
			type: 'equipment',
			stats: { attack: 12 },
		},
		{
			id: 'iron_mace',
			emoji: '🔨',
			nameKey: 'adventure.shop.items.iron_mace.name',
			descKey: 'adventure.shop.items.iron_mace.desc',
			price: 120,
			buyable: true,
			sellPrice: 60,
			type: 'equipment',
			stats: { attack: 14 },
		},
		{
			id: 'spear',
			emoji: '🔱',
			nameKey: 'adventure.shop.items.spear.name',
			descKey: 'adventure.shop.items.spear.desc',
			price: 130,
			buyable: true,
			sellPrice: 65,
			type: 'equipment',
			stats: { attack: 14 },
		},
		{
			id: 'battle_axe',
			emoji: '🪓',
			nameKey: 'adventure.shop.items.battle_axe.name',
			descKey: 'adventure.shop.items.battle_axe.desc',
			price: 150,
			buyable: true,
			sellPrice: 75,
			type: 'equipment',
			stats: { attack: 15 },
		},
		{
			id: 'long_sword',
			emoji: '⚔️',
			nameKey: 'adventure.shop.items.long_sword.name',
			descKey: 'adventure.shop.items.long_sword.desc',
			price: 180,
			buyable: true,
			sellPrice: 90,
			type: 'equipment',
			stats: { attack: 16 },
		},
		{
			id: 'crossbow',
			emoji: '🏹',
			nameKey: 'adventure.shop.items.crossbow.name',
			descKey: 'adventure.shop.items.crossbow.desc',
			price: 200,
			buyable: true,
			sellPrice: 100,
			type: 'equipment',
			stats: { attack: 18 },
		},

		{
			id: 'steel_sword',
			emoji: '⚔️',
			nameKey: 'adventure.shop.items.steel_sword.name',
			descKey: 'adventure.shop.items.steel_sword.desc',
			price: 300,
			buyable: true,
			sellPrice: 150,
			type: 'equipment',
			stats: { attack: 20 },
		},
		{
			id: 'steel_halberd',
			emoji: '🔱',
			nameKey: 'adventure.shop.items.steel_halberd.name',
			descKey: 'adventure.shop.items.steel_halberd.desc',
			price: 350,
			buyable: true,
			sellPrice: 175,
			type: 'equipment',
			stats: { attack: 22 },
		},
		{
			id: 'war_hammer',
			emoji: '🔨',
			nameKey: 'adventure.shop.items.war_hammer.name',
			descKey: 'adventure.shop.items.war_hammer.desc',
			price: 380,
			buyable: true,
			sellPrice: 190,
			type: 'equipment',
			stats: { attack: 22 },
		},
		{
			id: 'katana',
			emoji: '🗡️',
			nameKey: 'adventure.shop.items.katana.name',
			descKey: 'adventure.shop.items.katana.desc',
			price: 450,
			buyable: true,
			sellPrice: 225,
			type: 'equipment',
			stats: { attack: 24 },
		},
		{
			id: 'great_sword',
			emoji: '⚔️',
			nameKey: 'adventure.shop.items.great_sword.name',
			descKey: 'adventure.shop.items.great_sword.desc',
			price: 500,
			buyable: true,
			sellPrice: 250,
			type: 'equipment',
			stats: { attack: 25 },
		},
		{
			id: 'obsidian_blade',
			emoji: '⚫',
			nameKey: 'adventure.shop.items.obsidian_blade.name',
			descKey: 'adventure.shop.items.obsidian_blade.desc',
			price: 600,
			buyable: true,
			sellPrice: 300,
			type: 'equipment',
			stats: { attack: 28 },
		},
		{
			id: 'obsidian_scythe',
			emoji: '⛏️',
			nameKey: 'adventure.shop.items.obsidian_scythe.name',
			descKey: 'adventure.shop.items.obsidian_scythe.desc',
			price: 700,
			buyable: true,
			sellPrice: 350,
			type: 'equipment',
			stats: { attack: 30 },
		},

		{
			id: 'mithril_blade',
			emoji: '✨',
			nameKey: 'adventure.shop.items.mithril_blade.name',
			descKey: 'adventure.shop.items.mithril_blade.desc',
			price: 1000,
			buyable: true,
			sellPrice: 500,
			type: 'equipment',
			stats: { attack: 35 },
		},
		{
			id: 'mithril_bow',
			emoji: '🏹',
			nameKey: 'adventure.shop.items.mithril_bow.name',
			descKey: 'adventure.shop.items.mithril_bow.desc',
			price: 1200,
			buyable: true,
			sellPrice: 600,
			type: 'equipment',
			stats: { attack: 38 },
		},
		{
			id: 'crystal_sword',
			emoji: '💎',
			nameKey: 'adventure.shop.items.crystal_sword.name',
			descKey: 'adventure.shop.items.crystal_sword.desc',
			price: 1500,
			buyable: true,
			sellPrice: 750,
			type: 'equipment',
			stats: { attack: 40 },
		},
		{
			id: 'crystal_wand',
			emoji: '🪄',
			nameKey: 'adventure.shop.items.crystal_wand.name',
			descKey: 'adventure.shop.items.crystal_wand.desc',
			price: 1800,
			buyable: true,
			sellPrice: 900,
			type: 'equipment',
			stats: { attack: 42 },
		},
		{
			id: 'demon_blade',
			emoji: '👿',
			nameKey: 'adventure.shop.items.demon_blade.name',
			descKey: 'adventure.shop.items.demon_blade.desc',
			price: 2000,
			buyable: true,
			sellPrice: 1000,
			type: 'equipment',
			stats: { attack: 45 },
		},

		{
			id: 'dragon_slayer',
			emoji: '🐉',
			nameKey: 'adventure.shop.items.dragon_slayer.name',
			descKey: 'adventure.shop.items.dragon_slayer.desc',
			price: 5000,
			buyable: true,
			sellPrice: 2500,
			type: 'equipment',
			stats: { attack: 50 },
		},
		{
			id: 'excalibur',
			emoji: '🗡️',
			nameKey: 'adventure.shop.items.excalibur.name',
			descKey: 'adventure.shop.items.excalibur.desc',
			price: 7500,
			buyable: true,
			sellPrice: 3750,
			type: 'equipment',
			stats: { attack: 60 },
		},
		{
			id: 'void_staff',
			emoji: '🌌',
			nameKey: 'adventure.shop.items.void_staff.name',
			descKey: 'adventure.shop.items.void_staff.desc',
			price: 10000,
			buyable: true,
			sellPrice: 5000,
			type: 'equipment',
			stats: { attack: 65 },
		},
		{
			id: 'god_killer',
			emoji: '🔥',
			nameKey: 'adventure.shop.items.god_killer.name',
			descKey: 'adventure.shop.items.god_killer.desc',
			price: 20000,
			buyable: true,
			sellPrice: 10000,
			type: 'equipment',
			stats: { attack: 80 },
		},

		{
			id: 'leather_cap',
			emoji: '🧢',
			nameKey: 'adventure.shop.items.leather_cap.name',
			descKey: 'adventure.shop.items.leather_cap.desc',
			price: 15,
			buyable: true,
			sellPrice: 7,
			type: 'equipment',
			stats: { defense: 2 },
		},
		{
			id: 'bronze_helm',
			emoji: '🥉',
			nameKey: 'adventure.shop.items.bronze_helm.name',
			descKey: 'adventure.shop.items.bronze_helm.desc',
			price: 40,
			buyable: true,
			sellPrice: 20,
			type: 'equipment',
			stats: { defense: 3 },
		},
		{
			id: 'copper_helm',
			emoji: '🟠',
			nameKey: 'adventure.shop.items.copper_helm.name',
			descKey: 'adventure.shop.items.copper_helm.desc',
			price: 60,
			buyable: true,
			sellPrice: 30,
			type: 'equipment',
			stats: { defense: 4 },
		},
		{
			id: 'iron_helm',
			emoji: '🛡️',
			nameKey: 'adventure.shop.items.iron_helm.name',
			descKey: 'adventure.shop.items.iron_helm.desc',
			price: 100,
			buyable: true,
			sellPrice: 50,
			type: 'equipment',
			stats: { defense: 6 },
		},
		{
			id: 'steel_helm',
			emoji: '🛡️',
			nameKey: 'adventure.shop.items.steel_helm.name',
			descKey: 'adventure.shop.items.steel_helm.desc',
			price: 250,
			buyable: true,
			sellPrice: 125,
			type: 'equipment',
			stats: { defense: 10 },
		},
		{
			id: 'obsidian_helm',
			emoji: '⚫',
			nameKey: 'adventure.shop.items.obsidian_helm.name',
			descKey: 'adventure.shop.items.obsidian_helm.desc',
			price: 500,
			buyable: true,
			sellPrice: 250,
			type: 'equipment',
			stats: { defense: 15 },
		},
		{
			id: 'mithril_helm',
			emoji: '✨',
			nameKey: 'adventure.shop.items.mithril_helm.name',
			descKey: 'adventure.shop.items.mithril_helm.desc',
			price: 1000,
			buyable: true,
			sellPrice: 500,
			type: 'equipment',
			stats: { defense: 20 },
		},
		{
			id: 'dragon_helm',
			emoji: '🐉',
			nameKey: 'adventure.shop.items.dragon_helm.name',
			descKey: 'adventure.shop.items.dragon_helm.desc',
			price: 3000,
			buyable: true,
			sellPrice: 1500,
			type: 'equipment',
			stats: { defense: 30 },
		},

		{
			id: 'cloth_tunic',
			emoji: '👕',
			nameKey: 'adventure.shop.items.cloth_tunic.name',
			descKey: 'adventure.shop.items.cloth_tunic.desc',
			price: 10,
			buyable: true,
			sellPrice: 5,
			type: 'equipment',
			stats: { defense: 2 },
		},
		{
			id: 'leather_armor',
			emoji: '🥋',
			nameKey: 'adventure.shop.items.leather_armor.name',
			descKey: 'adventure.shop.items.leather_armor.desc',
			price: 30,
			buyable: true,
			sellPrice: 15,
			type: 'equipment',
			stats: { defense: 5 },
		},
		{
			id: 'bronze_armor',
			emoji: '🥉',
			nameKey: 'adventure.shop.items.bronze_armor.name',
			descKey: 'adventure.shop.items.bronze_armor.desc',
			price: 80,
			buyable: true,
			sellPrice: 40,
			type: 'equipment',
			stats: { defense: 8 },
		},
		{
			id: 'chainmail',
			emoji: '⛓️',
			nameKey: 'adventure.shop.items.chainmail.name',
			descKey: 'adventure.shop.items.chainmail.desc',
			price: 150,
			buyable: true,
			sellPrice: 75,
			type: 'equipment',
			stats: { defense: 12 },
		},
		{
			id: 'iron_armor',
			emoji: '🛡️',
			nameKey: 'adventure.shop.items.iron_armor.name',
			descKey: 'adventure.shop.items.iron_armor.desc',
			price: 300,
			buyable: true,
			sellPrice: 150,
			type: 'equipment',
			stats: { defense: 18 },
		},
		{
			id: 'steel_armor',
			emoji: '🛡️',
			nameKey: 'adventure.shop.items.steel_armor.name',
			descKey: 'adventure.shop.items.steel_armor.desc',
			price: 600,
			buyable: true,
			sellPrice: 300,
			type: 'equipment',
			stats: { defense: 25 },
		},
		{
			id: 'obsidian_armor',
			emoji: '⚫',
			nameKey: 'adventure.shop.items.obsidian_armor.name',
			descKey: 'adventure.shop.items.obsidian_armor.desc',
			price: 1200,
			buyable: true,
			sellPrice: 600,
			type: 'equipment',
			stats: { defense: 35 },
		},
		{
			id: 'mithril_armor',
			emoji: '✨',
			nameKey: 'adventure.shop.items.mithril_armor.name',
			descKey: 'adventure.shop.items.mithril_armor.desc',
			price: 2500,
			buyable: true,
			sellPrice: 1250,
			type: 'equipment',
			stats: { defense: 45 },
		},
		{
			id: 'crystal_armor',
			emoji: '💎',
			nameKey: 'adventure.shop.items.crystal_armor.name',
			descKey: 'adventure.shop.items.crystal_armor.desc',
			price: 4000,
			buyable: true,
			sellPrice: 2000,
			type: 'equipment',
			stats: { defense: 55 },
		},
		{
			id: 'dragon_armor',
			emoji: '🐉',
			nameKey: 'adventure.shop.items.dragon_armor.name',
			descKey: 'adventure.shop.items.dragon_armor.desc',
			price: 8000,
			buyable: true,
			sellPrice: 4000,
			type: 'equipment',
			stats: { defense: 70 },
		},

		{
			id: 'wooden_shield',
			emoji: '🛡️',
			nameKey: 'adventure.shop.items.wooden_shield.name',
			descKey: 'adventure.shop.items.wooden_shield.desc',
			price: 15,
			buyable: true,
			sellPrice: 7,
			type: 'equipment',
			stats: { defense: 3 },
		},
		{
			id: 'buckler',
			emoji: '🛡️',
			nameKey: 'adventure.shop.items.buckler.name',
			descKey: 'adventure.shop.items.buckler.desc',
			price: 30,
			buyable: true,
			sellPrice: 15,
			type: 'equipment',
			stats: { defense: 5 },
		},
		{
			id: 'bronze_shield',
			emoji: '🥉',
			nameKey: 'adventure.shop.items.bronze_shield.name',
			descKey: 'adventure.shop.items.bronze_shield.desc',
			price: 60,
			buyable: true,
			sellPrice: 30,
			type: 'equipment',
			stats: { defense: 7 },
		},
		{
			id: 'iron_shield',
			emoji: '🛡️',
			nameKey: 'adventure.shop.items.iron_shield.name',
			descKey: 'adventure.shop.items.iron_shield.desc',
			price: 120,
			buyable: true,
			sellPrice: 60,
			type: 'equipment',
			stats: { defense: 10 },
		},
		{
			id: 'steel_shield',
			emoji: '🛡️',
			nameKey: 'adventure.shop.items.steel_shield.name',
			descKey: 'adventure.shop.items.steel_shield.desc',
			price: 250,
			buyable: true,
			sellPrice: 125,
			type: 'equipment',
			stats: { defense: 15 },
		},
		{
			id: 'tower_shield',
			emoji: '🛡️',
			nameKey: 'adventure.shop.items.tower_shield.name',
			descKey: 'adventure.shop.items.tower_shield.desc',
			price: 400,
			buyable: true,
			sellPrice: 200,
			type: 'equipment',
			stats: { defense: 18 },
		},
		{
			id: 'obsidian_shield',
			emoji: '⚫',
			nameKey: 'adventure.shop.items.obsidian_shield.name',
			descKey: 'adventure.shop.items.obsidian_shield.desc',
			price: 800,
			buyable: true,
			sellPrice: 400,
			type: 'equipment',
			stats: { defense: 25 },
		},
		{
			id: 'mithril_shield',
			emoji: '✨',
			nameKey: 'adventure.shop.items.mithril_shield.name',
			descKey: 'adventure.shop.items.mithril_shield.desc',
			price: 1500,
			buyable: true,
			sellPrice: 750,
			type: 'equipment',
			stats: { defense: 35 },
		},
		{
			id: 'aegis',
			emoji: '🛡️',
			nameKey: 'adventure.shop.items.aegis.name',
			descKey: 'adventure.shop.items.aegis.desc',
			price: 5000,
			buyable: true,
			sellPrice: 2500,
			type: 'equipment',
			stats: { defense: 50 },
		},
	],
	consumables: [
		{
			id: 'apple',
			emoji: '🍎',
			nameKey: 'adventure.shop.items.apple.name',
			descKey: 'adventure.shop.items.apple.desc',
			price: 5,
			buyable: true,
			sellPrice: 2,
			type: 'consumable',
			effect: 'heal',
			amount: 10,
			uses: 1,
		},
		{
			id: 'bandage',
			emoji: '🩹',
			nameKey: 'adventure.shop.items.bandage.name',
			descKey: 'adventure.shop.items.bandage.desc',
			price: 10,
			buyable: true,
			sellPrice: 5,
			type: 'consumable',
			effect: 'heal',
			amount: 15,
			uses: 1,
		},
		{
			id: 'bread',
			emoji: '🍞',
			nameKey: 'adventure.shop.items.bread.name',
			descKey: 'adventure.shop.items.bread.desc',
			price: 15,
			buyable: true,
			sellPrice: 7,
			type: 'consumable',
			effect: 'heal',
			amount: 20,
			uses: 1,
		},
		{
			id: 'small_health_potion',
			emoji: '🍷',
			nameKey: 'adventure.shop.items.small_health_potion.name',
			descKey: 'adventure.shop.items.small_health_potion.desc',
			price: 25,
			buyable: true,
			sellPrice: 12,
			type: 'consumable',
			effect: 'heal',
			amount: 30,
			uses: 1,
		},
		{
			id: 'health_potion',
			emoji: '❤️',
			nameKey: 'adventure.shop.items.health_potion.name',
			descKey: 'adventure.shop.items.health_potion.desc',
			price: 50,
			buyable: true,
			sellPrice: 25,
			type: 'consumable',
			effect: 'heal',
			amount: 50,
			uses: 1,
		},
		{
			id: 'great_health_potion',
			emoji: '💖',
			nameKey: 'adventure.shop.items.great_health_potion.name',
			descKey: 'adventure.shop.items.great_health_potion.desc',
			price: 100,
			buyable: true,
			sellPrice: 50,
			type: 'consumable',
			effect: 'heal',
			amount: 100,
			uses: 1,
		},
		{
			id: 'super_potion',
			emoji: '💗',
			nameKey: 'adventure.shop.items.super_potion.name',
			descKey: 'adventure.shop.items.super_potion.desc',
			price: 200,
			buyable: true,
			sellPrice: 100,
			type: 'consumable',
			effect: 'heal',
			amount: 200,
			uses: 1,
		},
		{
			id: 'hyper_potion',
			emoji: '💓',
			nameKey: 'adventure.shop.items.hyper_potion.name',
			descKey: 'adventure.shop.items.hyper_potion.desc',
			price: 500,
			buyable: true,
			sellPrice: 250,
			type: 'consumable',
			effect: 'heal',
			amount: 500,
			uses: 1,
		},
		{
			id: 'max_potion',
			emoji: '💞',
			nameKey: 'adventure.shop.items.max_potion.name',
			descKey: 'adventure.shop.items.max_potion.desc',
			price: 1000,
			buyable: true,
			sellPrice: 500,
			type: 'consumable',
			effect: 'heal',
			amount: 9999,
			uses: 1,
		},
		{
			id: 'revival',
			emoji: '🍶',
			nameKey: 'adventure.shop.items.revival.name',
			descKey: 'adventure.shop.items.revival.desc',
			price: 100,
			buyable: true,
			sellPrice: 50,
			type: 'consumable',
			effect: 'revive',
			uses: 1,
		},
	],
};
/**
 * Retrieves the item definition object from its display name (as stored in inventory).
 * Supports both equipment and consumables.
 * @param {string} itemName - The display name of the item (may include emoji).
 * @returns {object|null} Item object if found, else null.
 */
function getItem(itemName) {
	const categories = ['equipment', 'consumables'];
	for (const cat of categories) {
		for (const item of items[cat]) {
			const localizedName = `${item.emoji} ${getLocalizedItemName(item)}`;
			if (
				itemName === localizedName ||
				itemName === getLocalizedItemName(item)
			) {
				return {
					...item,
					name: localizedName,
					description: getLocalizedItemDesc(item),
				};
			}
		}
	}
	return null;
}

function getItemById(itemId) {
	const allItems = [...items.equipment, ...items.consumables];
	return allItems.find((i) => i.id === itemId) || null;
}

/**
 * Helper to get the localized item name.
 * Replace this with translation lookup as needed.
 */
function getLocalizedItemName(item) {
	if (item.nameKey) {
		return (
			item.emoji +
			' ' +
			item.id.replace('_', ' ').replace(/\b\w/g, (l) => l.toUpperCase())
		);
	}
	return `${item.emoji} ${item.id}`;
}

/**
 * Helper to get the localized item description.
 * Replace this with translation lookup as needed.
 */
function getLocalizedItemDesc(item) {
	if (item.descKey) {
		return 'adventure.items.no_desc';
	}
	return '';
}

module.exports = {
	items,
	getItem,
	getItemById,
};
