/**
 * @namespace: addons/adventure/helpers/monster.js
 * @type: Helper Script
 * @copyright © 2025 kenndeclouv
 * @assistant chaa & graa
 * @version 0.11.0-beta
 */

const MONSTERS = [
	{
		name: 'Wild Dog',
		nameKey: 'adventure.monsters.wild_dog',
		hp: 42,
		strength: 12,
		goldDrop: 16,
		xpDrop: 13,
		minLevel: 2,
		maxLevel: 3,
	},
	{
		name: 'Rat',
		nameKey: 'adventure.monsters.rat',
		hp: 30,
		strength: 7,
		goldDrop: 10,
		xpDrop: 8,
		minLevel: 1,
		maxLevel: 2,
	},
	{
		name: 'Bat',
		nameKey: 'adventure.monsters.bat',
		hp: 28,
		strength: 6,
		goldDrop: 9,
		xpDrop: 7,
		minLevel: 1,
		maxLevel: 2,
	},
	{
		name: 'Slime',
		nameKey: 'adventure.monsters.slime',
		hp: 25,
		strength: 5,
		goldDrop: 7,
		xpDrop: 5,
		minLevel: 1,
		maxLevel: 2,
	},
	{
		name: 'Goblin',
		nameKey: 'adventure.monsters.goblin',
		hp: 38,
		strength: 10,
		goldDrop: 14,
		xpDrop: 12,
		minLevel: 2,
		maxLevel: 3,
	},

	{
		name: 'Orc',
		nameKey: 'adventure.monsters.orc',
		hp: 160,
		strength: 25,
		goldDrop: 40,
		xpDrop: 35,
		minLevel: 3,
		maxLevel: 4,
	},
	{
		name: 'Giant Spider',
		nameKey: 'adventure.monsters.giant_spider',
		hp: 140,
		strength: 22,
		goldDrop: 35,
		xpDrop: 32,
		minLevel: 3,
		maxLevel: 4,
	},
	{
		name: 'Skeleton',
		nameKey: 'adventure.monsters.skeleton',
		hp: 120,
		strength: 20,
		goldDrop: 32,
		xpDrop: 28,
		minLevel: 3,
		maxLevel: 4,
	},
	{
		name: 'Zombie',
		nameKey: 'adventure.monsters.zombie',
		hp: 150,
		strength: 24,
		goldDrop: 38,
		xpDrop: 31,
		minLevel: 3,
		maxLevel: 4,
	},
	{
		name: 'Bandit',
		nameKey: 'adventure.monsters.bandit',
		hp: 130,
		strength: 27,
		goldDrop: 45,
		xpDrop: 34,
		minLevel: 4,
		maxLevel: 5,
	},

	{
		name: 'Wyvern',
		nameKey: 'adventure.monsters.wyvern',
		hp: 400,
		strength: 70,
		goldDrop: 110,
		xpDrop: 100,
		minLevel: 5,
		maxLevel: 6,
	},
	{
		name: 'Vampire',
		nameKey: 'adventure.monsters.vampire',
		hp: 220,
		strength: 45,
		goldDrop: 60,
		xpDrop: 55,
		minLevel: 5,
		maxLevel: 6,
	},
	{
		name: 'Troll',
		nameKey: 'adventure.monsters.troll',
		hp: 320,
		strength: 55,
		goldDrop: 90,
		xpDrop: 75,
		minLevel: 5,
		maxLevel: 6,
	},
	{
		name: 'Werewolf',
		nameKey: 'adventure.monsters.werewolf',
		hp: 260,
		strength: 50,
		goldDrop: 80,
		xpDrop: 65,
		minLevel: 5,
		maxLevel: 6,
	},
	{
		name: 'Dark Mage',
		nameKey: 'adventure.monsters.dark_mage',
		hp: 200,
		strength: 65,
		goldDrop: 100,
		xpDrop: 90,
		minLevel: 6,
		maxLevel: 7,
	},

	{
		name: 'Behemoth',
		nameKey: 'adventure.monsters.behemoth',
		hp: 700,
		strength: 120,
		goldDrop: 250,
		xpDrop: 200,
		minLevel: 7,
		maxLevel: 8,
	},
	{
		name: 'Phoenix',
		nameKey: 'adventure.monsters.phoenix',
		hp: 600,
		strength: 110,
		goldDrop: 230,
		xpDrop: 180,
		minLevel: 7,
		maxLevel: 8,
	},
	{
		name: 'Hydra',
		nameKey: 'adventure.monsters.hydra',
		hp: 550,
		strength: 105,
		goldDrop: 220,
		xpDrop: 170,
		minLevel: 7,
		maxLevel: 8,
	},
	{
		name: 'Lich King',
		nameKey: 'adventure.monsters.lich_king',
		hp: 520,
		strength: 130,
		goldDrop: 270,
		xpDrop: 220,
		minLevel: 8,
		maxLevel: 9,
	},
	{
		name: 'Ancient Golem',
		nameKey: 'adventure.monsters.ancient_golem',
		hp: 650,
		strength: 120,
		goldDrop: 240,
		xpDrop: 190,
		minLevel: 8,
		maxLevel: 9,
	},

	{
		name: 'Dragon',
		nameKey: 'adventure.monsters.dragon',
		hp: 900,
		strength: 170,
		goldDrop: 350,
		xpDrop: 320,
		minLevel: 9,
		maxLevel: 99,
	},
	{
		name: 'Demon Lord',
		nameKey: 'adventure.monsters.demon_lord',
		hp: 1100,
		strength: 210,
		goldDrop: 420,
		xpDrop: 400,
		minLevel: 10,
		maxLevel: 99,
	},
	{
		name: 'Celestial Serpent',
		nameKey: 'adventure.monsters.celestial_serpent',
		hp: 1000,
		strength: 190,
		goldDrop: 390,
		xpDrop: 360,
		minLevel: 10,
		maxLevel: 99,
	},
	{
		name: 'Shadow Reaper',
		nameKey: 'adventure.monsters.shadow_reaper',
		hp: 880,
		strength: 180,
		goldDrop: 360,
		xpDrop: 300,
		minLevel: 9,
		maxLevel: 99,
	},
	{
		name: 'Titan',
		nameKey: 'adventure.monsters.titan',
		hp: 1400,
		strength: 240,
		goldDrop: 500,
		xpDrop: 480,
		minLevel: 12,
		maxLevel: 99,
	},
];

function getRandomMonster(level) {
	const available = MONSTERS.filter(
		(m) => level >= m.minLevel && level <= m.maxLevel,
	);
	if (available.length === 0) {
		return MONSTERS[Math.floor(Math.random() * MONSTERS.length)];
	}
	return available[Math.floor(Math.random() * available.length)];
}

module.exports = {
	getRandomMonster,
};
