// biome-ignore-all lint/suspicious/noExplicitAny: auto generated
// 🛑 DO NOT EDIT. Auto-generated by "bunx kythia di:generate"
// 🧙‍♂️ The Type Wizard - Smart Mode

export {};

declare global {
	namespace KythiaDI {
		interface Container {
			// --- Core Services ---
			client: import('discord.js').Client;
			sequelize: import('sequelize').Sequelize;
			redis: import('ioredis').default;
			kythiaConfig: any;
			t: (interaction: any, key: string, args?: any) => Promise<string>;

			// --- Models ---
			models: {
				Checklist: typeof import('@addons/checklist/database/models/Checklist');
				DnsRecord: typeof import('@addons/pro/database/models/DnsRecord');
				Favorite: typeof import('@addons/music/database/models/Favorite');
				Giveaway: typeof import('@addons/giveaway/database/models/Giveaway');
				GlobalChat: typeof import('@addons/globalchat/database/models/GlobalChat');
				Image: typeof import('@addons/image/database/models/Image');
				Inventory: typeof import('@addons/core/database/models/Inventory');
				InventoryAdventure: typeof import('@addons/adventure/database/models/InventoryAdventure');
				Invite: typeof import('@addons/invite/database/models/Invite');
				InviteHistory: typeof import('@addons/invite/database/models/InviteHistory');
				KythiaSetting: typeof import('@addons/core/database/models/KythiaSetting');
				KythiaTeam: typeof import('@addons/core/database/models/KythiaTeam');
				KythiaUser: typeof import('@addons/core/database/models/KythiaUser');
				KythiaVoter: typeof import('@addons/core/database/models/KythiaVoter');
				MarketOrder: typeof import('@addons/economy/database/models/MarketOrder');
				MarketPortfolio: typeof import('@addons/economy/database/models/MarketPortfolio');
				MarketTransaction: typeof import('@addons/economy/database/models/MarketTransaction');
				Marriage: typeof import('@addons/fun/database/models/Marriage');
				ModLog: typeof import('@addons/core/database/models/ModLog');
				Monitor: typeof import('@addons/pro/database/models/Monitor');
				Music247: typeof import('@addons/music/database/models/Music247');
				Password: typeof import('@addons/core/database/models/Password');
				Pet: typeof import('@addons/pet/database/models/Pet');
				Playlist: typeof import('@addons/music/database/models/Playlist');
				PlaylistTrack: typeof import('@addons/music/database/models/PlaylistTrack');
				QuestConfig: typeof import('@addons/quest/database/models/QuestConfig');
				QuestGuildLog: typeof import('@addons/quest/database/models/QuestGuildLog');
				ServerSetting: typeof import('@addons/core/database/models/ServerSetting');
				Snipe: typeof import('@addons/core/database/models/Snipe');
				StickyMessage: typeof import('@addons/core/database/models/StickyMessage');
				Streak: typeof import('@addons/streak/database/models/Streak');
				Subdomain: typeof import('@addons/pro/database/models/Subdomain');
				TempVoiceChannel: typeof import('@addons/tempvoice/database/models/TempVoiceChannel');
				TempVoiceConfig: typeof import('@addons/tempvoice/database/models/TempVoiceConfig');
				Ticket: typeof import('@addons/ticket/database/models/Ticket');
				TicketConfig: typeof import('@addons/ticket/database/models/TicketConfig');
				TicketPanel: typeof import('@addons/ticket/database/models/TicketPanel');
				User: typeof import('@addons/core/database/models/User');
				UserAFK: typeof import('@addons/core/database/models/UserAFK');
				UserAdventure: typeof import('@addons/adventure/database/models/UserAdventure');
				UserFact: typeof import('@addons/ai/database/models/UserFact');
				UserPet: typeof import('@addons/pet/database/models/UserPet');
			};
			// --- Helpers (Injected in index.js) ---
			helpers: {
				discord: typeof import('@coreHelpers/discord');
				color: { convertColor: (color: any, opts?: any) => number };
				time: typeof import('@addons/core/helpers/time');
			};
		}
	}
}
